token: ""
url: "http://localhost:8080/"
engine:
  dir: ""
  name: ""
  protocol: "uci"
  online_moves:
    max_depth: 10
    chessdb_book:
      enabled: true
      move_quality: "good"
challenge:
  accept_bot: true
  time_controls:
    - bullet
    - blitz
    - rapid
    - classical
  modes:
    - casual
    - rated
  variants:
    - standard