token: ""
url: "http://localhost:8080/"
engine:
  dir: ""
  name: ""
  protocol: "uci"
  lichess_cloud_analysis:
    enabled: true
    move_quality: "good"
challenge:
  accept_bot: true
  time_controls:
    - bullet
    - blitz
    - rapid
    - classical
  modes:
    - casual
    - rated
  variants:
    - standard